//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDH.FxSignalPro.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FxSignalProEntities : DbContext
    {
        public FxSignalProEntities()
            : base("name=FxSignalProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<CurrencyPair> CurrencyPairs { get; set; }
        public virtual DbSet<SellerProfile> SellerProfiles { get; set; }
        public virtual DbSet<Signal> Signals { get; set; }
        public virtual DbSet<SupportedSellingCurrency> SupportedSellingCurrencies { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TimeFrame> TimeFrames { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserSellerFollowing> UserSellerFollowings { get; set; }
        public virtual DbSet<UserSignalLike> UserSignalLikes { get; set; }
        public virtual DbSet<UserSignal> UserSignals { get; set; }
    }
}
