//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDH.FxSignalPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerProfile
    {
        public SellerProfile()
        {
            this.Signals = new HashSet<Signal>();
            this.UserSellerFollowings = new HashSet<UserSellerFollowing>();
        }
    
        public System.Guid SellerProfileId { get; set; }
        public string SellerName { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Deleted { get; set; }
        public System.DateTime Modified { get; set; }
        public string ModifiledBy { get; set; }
    
        public virtual ICollection<Signal> Signals { get; set; }
        public virtual ICollection<UserSellerFollowing> UserSellerFollowings { get; set; }
    }
}
