//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDH.FxSignalPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.UserSellerFollowings = new HashSet<UserSellerFollowing>();
            this.UserSignalLikes = new HashSet<UserSignalLike>();
            this.UserSignals = new HashSet<UserSignal>();
        }
    
        public System.Guid UserId { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<UserSellerFollowing> UserSellerFollowings { get; set; }
        public virtual ICollection<UserSignalLike> UserSignalLikes { get; set; }
        public virtual ICollection<UserSignal> UserSignals { get; set; }
    }
}
